// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rzuupvxigzdvnwlrcevo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ6dXVwdnhpZ3pkdm53bHJjZXZvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcwNDM4MjYsImV4cCI6MjA2MjYxOTgyNn0.jDF-5Y8QZAZbcuRq80MkXZWaxw3vG2sxSZyubi3xWIo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);