// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://faptkprexucaqazvhxqz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZhcHRrcHJleHVjYXFhenZoeHF6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3MjA2NjIsImV4cCI6MjA2MDI5NjY2Mn0.hHAodizYiShFUBay2dk4He8LJTRpimhuud52_347q0M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);